package com.jie.literature.domain;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_id
     *
     * @mbggenerated
     */
    private Integer artId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_type
     *
     * @mbggenerated
     */
    private String artType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_title
     *
     * @mbggenerated
     */
    private String artTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_text
     *
     * @mbggenerated
     */
    private String artText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_uid
     *
     * @mbggenerated
     */
    private Integer artUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_createtime
     *
     * @mbggenerated
     */
    private Date artCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_status
     *
     * @mbggenerated
     */
    private Integer artStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_fid
     *
     * @mbggenerated
     */
    private Integer artFid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_id
     *
     * @return the value of article.art_id
     *
     * @mbggenerated
     */
    public Integer getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_id
     *
     * @param artId the value for article.art_id
     *
     * @mbggenerated
     */
    public void setArtId(Integer artId) {
        this.artId = artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_type
     *
     * @return the value of article.art_type
     *
     * @mbggenerated
     */
    public String getArtType() {
        return artType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_type
     *
     * @param artType the value for article.art_type
     *
     * @mbggenerated
     */
    public void setArtType(String artType) {
        this.artType = artType == null ? null : artType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_title
     *
     * @return the value of article.art_title
     *
     * @mbggenerated
     */
    public String getArtTitle() {
        return artTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_title
     *
     * @param artTitle the value for article.art_title
     *
     * @mbggenerated
     */
    public void setArtTitle(String artTitle) {
        this.artTitle = artTitle == null ? null : artTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_text
     *
     * @return the value of article.art_text
     *
     * @mbggenerated
     */
    public String getArtText() {
        return artText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_text
     *
     * @param artText the value for article.art_text
     *
     * @mbggenerated
     */
    public void setArtText(String artText) {
        this.artText = artText == null ? null : artText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_uid
     *
     * @return the value of article.art_uid
     *
     * @mbggenerated
     */
    public Integer getArtUid() {
        return artUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_uid
     *
     * @param artUid the value for article.art_uid
     *
     * @mbggenerated
     */
    public void setArtUid(Integer artUid) {
        this.artUid = artUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_createtime
     *
     * @return the value of article.art_createtime
     *
     * @mbggenerated
     */
    public Date getArtCreatetime() {
        return artCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_createtime
     *
     * @param artCreatetime the value for article.art_createtime
     *
     * @mbggenerated
     */
    public void setArtCreatetime(Date artCreatetime) {
        this.artCreatetime = artCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_status
     *
     * @return the value of article.art_status
     *
     * @mbggenerated
     */
    public Integer getArtStatus() {
        return artStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_status
     *
     * @param artStatus the value for article.art_status
     *
     * @mbggenerated
     */
    public void setArtStatus(Integer artStatus) {
        this.artStatus = artStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_fid
     *
     * @return the value of article.art_fid
     *
     * @mbggenerated
     */
    public Integer getArtFid() {
        return artFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_fid
     *
     * @param artFid the value for article.art_fid
     *
     * @mbggenerated
     */
    public void setArtFid(Integer artFid) {
        this.artFid = artFid;
    }
}