package com.jie.literature.domain;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_id
     *
     * @mbggenerated
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_uid
     *
     * @mbggenerated
     */
    private Integer comUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_aid
     *
     * @mbggenerated
     */
    private Integer comAid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_text
     *
     * @mbggenerated
     */
    private String comText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_createtime
     *
     * @mbggenerated
     */
    private Date comCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_status
     *
     * @mbggenerated
     */
    private Integer comStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_id
     *
     * @return the value of comment.com_id
     *
     * @mbggenerated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_id
     *
     * @param comId the value for comment.com_id
     *
     * @mbggenerated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_uid
     *
     * @return the value of comment.com_uid
     *
     * @mbggenerated
     */
    public Integer getComUid() {
        return comUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_uid
     *
     * @param comUid the value for comment.com_uid
     *
     * @mbggenerated
     */
    public void setComUid(Integer comUid) {
        this.comUid = comUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_aid
     *
     * @return the value of comment.com_aid
     *
     * @mbggenerated
     */
    public Integer getComAid() {
        return comAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_aid
     *
     * @param comAid the value for comment.com_aid
     *
     * @mbggenerated
     */
    public void setComAid(Integer comAid) {
        this.comAid = comAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_text
     *
     * @return the value of comment.com_text
     *
     * @mbggenerated
     */
    public String getComText() {
        return comText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_text
     *
     * @param comText the value for comment.com_text
     *
     * @mbggenerated
     */
    public void setComText(String comText) {
        this.comText = comText == null ? null : comText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_createtime
     *
     * @return the value of comment.com_createtime
     *
     * @mbggenerated
     */
    public Date getComCreatetime() {
        return comCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_createtime
     *
     * @param comCreatetime the value for comment.com_createtime
     *
     * @mbggenerated
     */
    public void setComCreatetime(Date comCreatetime) {
        this.comCreatetime = comCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_status
     *
     * @return the value of comment.com_status
     *
     * @mbggenerated
     */
    public Integer getComStatus() {
        return comStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_status
     *
     * @param comStatus the value for comment.com_status
     *
     * @mbggenerated
     */
    public void setComStatus(Integer comStatus) {
        this.comStatus = comStatus;
    }
}