package com.jie.literature.domain;

import java.util.Date;

public class Fabulous {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fab_id
     *
     * @mbggenerated
     */
    private Integer fabId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fab_aid
     *
     * @mbggenerated
     */
    private Integer fabAid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fab_uid
     *
     * @mbggenerated
     */
    private Integer fabUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fab_createtime
     *
     * @mbggenerated
     */
    private Date fabCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fab_status
     *
     * @mbggenerated
     */
    private Integer fabStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fab_id
     *
     * @return the value of fabulous.fab_id
     *
     * @mbggenerated
     */
    public Integer getFabId() {
        return fabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fab_id
     *
     * @param fabId the value for fabulous.fab_id
     *
     * @mbggenerated
     */
    public void setFabId(Integer fabId) {
        this.fabId = fabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fab_aid
     *
     * @return the value of fabulous.fab_aid
     *
     * @mbggenerated
     */
    public Integer getFabAid() {
        return fabAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fab_aid
     *
     * @param fabAid the value for fabulous.fab_aid
     *
     * @mbggenerated
     */
    public void setFabAid(Integer fabAid) {
        this.fabAid = fabAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fab_uid
     *
     * @return the value of fabulous.fab_uid
     *
     * @mbggenerated
     */
    public Integer getFabUid() {
        return fabUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fab_uid
     *
     * @param fabUid the value for fabulous.fab_uid
     *
     * @mbggenerated
     */
    public void setFabUid(Integer fabUid) {
        this.fabUid = fabUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fab_createtime
     *
     * @return the value of fabulous.fab_createtime
     *
     * @mbggenerated
     */
    public Date getFabCreatetime() {
        return fabCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fab_createtime
     *
     * @param fabCreatetime the value for fabulous.fab_createtime
     *
     * @mbggenerated
     */
    public void setFabCreatetime(Date fabCreatetime) {
        this.fabCreatetime = fabCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fab_status
     *
     * @return the value of fabulous.fab_status
     *
     * @mbggenerated
     */
    public Integer getFabStatus() {
        return fabStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fab_status
     *
     * @param fabStatus the value for fabulous.fab_status
     *
     * @mbggenerated
     */
    public void setFabStatus(Integer fabStatus) {
        this.fabStatus = fabStatus;
    }
}