package com.jie.literature.domain;

import java.util.Date;

public class Follow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.fol_id
     *
     * @mbggenerated
     */
    private Integer folId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.fol_uid
     *
     * @mbggenerated
     */
    private Integer folUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.fol_userid
     *
     * @mbggenerated
     */
    private Integer folUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.fol_createtime
     *
     * @mbggenerated
     */
    private Date folCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.fol_status
     *
     * @mbggenerated
     */
    private Integer folStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.fol_id
     *
     * @return the value of follow.fol_id
     *
     * @mbggenerated
     */
    public Integer getFolId() {
        return folId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.fol_id
     *
     * @param folId the value for follow.fol_id
     *
     * @mbggenerated
     */
    public void setFolId(Integer folId) {
        this.folId = folId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.fol_uid
     *
     * @return the value of follow.fol_uid
     *
     * @mbggenerated
     */
    public Integer getFolUid() {
        return folUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.fol_uid
     *
     * @param folUid the value for follow.fol_uid
     *
     * @mbggenerated
     */
    public void setFolUid(Integer folUid) {
        this.folUid = folUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.fol_userid
     *
     * @return the value of follow.fol_userid
     *
     * @mbggenerated
     */
    public Integer getFolUserid() {
        return folUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.fol_userid
     *
     * @param folUserid the value for follow.fol_userid
     *
     * @mbggenerated
     */
    public void setFolUserid(Integer folUserid) {
        this.folUserid = folUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.fol_createtime
     *
     * @return the value of follow.fol_createtime
     *
     * @mbggenerated
     */
    public Date getFolCreatetime() {
        return folCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.fol_createtime
     *
     * @param folCreatetime the value for follow.fol_createtime
     *
     * @mbggenerated
     */
    public void setFolCreatetime(Date folCreatetime) {
        this.folCreatetime = folCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.fol_status
     *
     * @return the value of follow.fol_status
     *
     * @mbggenerated
     */
    public Integer getFolStatus() {
        return folStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.fol_status
     *
     * @param folStatus the value for follow.fol_status
     *
     * @mbggenerated
     */
    public void setFolStatus(Integer folStatus) {
        this.folStatus = folStatus;
    }
}