package com.jie.literature.domain;

import java.util.Date;

public class Massage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column massage.msg_id
     *
     * @mbggenerated
     */
    private Integer msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column massage.msg_suid
     *
     * @mbggenerated
     */
    private Integer msgSuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column massage.msg_text
     *
     * @mbggenerated
     */
    private String msgText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column massage.msg_createtime
     *
     * @mbggenerated
     */
    private Date msgCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column massage.msg_ruid
     *
     * @mbggenerated
     */
    private Integer msgRuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column massage.msg_status
     *
     * @mbggenerated
     */
    private Integer msgStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column massage.msg_id
     *
     * @return the value of massage.msg_id
     *
     * @mbggenerated
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column massage.msg_id
     *
     * @param msgId the value for massage.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column massage.msg_suid
     *
     * @return the value of massage.msg_suid
     *
     * @mbggenerated
     */
    public Integer getMsgSuid() {
        return msgSuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column massage.msg_suid
     *
     * @param msgSuid the value for massage.msg_suid
     *
     * @mbggenerated
     */
    public void setMsgSuid(Integer msgSuid) {
        this.msgSuid = msgSuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column massage.msg_text
     *
     * @return the value of massage.msg_text
     *
     * @mbggenerated
     */
    public String getMsgText() {
        return msgText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column massage.msg_text
     *
     * @param msgText the value for massage.msg_text
     *
     * @mbggenerated
     */
    public void setMsgText(String msgText) {
        this.msgText = msgText == null ? null : msgText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column massage.msg_createtime
     *
     * @return the value of massage.msg_createtime
     *
     * @mbggenerated
     */
    public Date getMsgCreatetime() {
        return msgCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column massage.msg_createtime
     *
     * @param msgCreatetime the value for massage.msg_createtime
     *
     * @mbggenerated
     */
    public void setMsgCreatetime(Date msgCreatetime) {
        this.msgCreatetime = msgCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column massage.msg_ruid
     *
     * @return the value of massage.msg_ruid
     *
     * @mbggenerated
     */
    public Integer getMsgRuid() {
        return msgRuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column massage.msg_ruid
     *
     * @param msgRuid the value for massage.msg_ruid
     *
     * @mbggenerated
     */
    public void setMsgRuid(Integer msgRuid) {
        this.msgRuid = msgRuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column massage.msg_status
     *
     * @return the value of massage.msg_status
     *
     * @mbggenerated
     */
    public Integer getMsgStatus() {
        return msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column massage.msg_status
     *
     * @param msgStatus the value for massage.msg_status
     *
     * @mbggenerated
     */
    public void setMsgStatus(Integer msgStatus) {
        this.msgStatus = msgStatus;
    }
}