package com.jie.literature.domain;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_suid
     *
     * @mbggenerated
     */
    private Integer newsSuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_ruid
     *
     * @mbggenerated
     */
    private Integer newsRuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbggenerated
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_text
     *
     * @mbggenerated
     */
    private String newsText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_status
     *
     * @mbggenerated
     */
    private Integer newsStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_suid
     *
     * @return the value of news.news_suid
     *
     * @mbggenerated
     */
    public Integer getNewsSuid() {
        return newsSuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_suid
     *
     * @param newsSuid the value for news.news_suid
     *
     * @mbggenerated
     */
    public void setNewsSuid(Integer newsSuid) {
        this.newsSuid = newsSuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_ruid
     *
     * @return the value of news.news_ruid
     *
     * @mbggenerated
     */
    public Integer getNewsRuid() {
        return newsRuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_ruid
     *
     * @param newsRuid the value for news.news_ruid
     *
     * @mbggenerated
     */
    public void setNewsRuid(Integer newsRuid) {
        this.newsRuid = newsRuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbggenerated
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbggenerated
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_text
     *
     * @return the value of news.news_text
     *
     * @mbggenerated
     */
    public String getNewsText() {
        return newsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_text
     *
     * @param newsText the value for news.news_text
     *
     * @mbggenerated
     */
    public void setNewsText(String newsText) {
        this.newsText = newsText == null ? null : newsText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_status
     *
     * @return the value of news.news_status
     *
     * @mbggenerated
     */
    public Integer getNewsStatus() {
        return newsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_status
     *
     * @param newsStatus the value for news.news_status
     *
     * @mbggenerated
     */
    public void setNewsStatus(Integer newsStatus) {
        this.newsStatus = newsStatus;
    }
}