package com.jie.literature.domain;

import java.util.Date;

public class Roundsow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roundsow.roun_id
     *
     * @mbggenerated
     */
    private Integer rounId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roundsow.roun_img
     *
     * @mbggenerated
     */
    private String rounImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roundsow.rpun_type
     *
     * @mbggenerated
     */
    private String rpunType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roundsow.roun_createtime
     *
     * @mbggenerated
     */
    private Date rounCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roundsow.roun_sort
     *
     * @mbggenerated
     */
    private Integer rounSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roundsow.roun_status
     *
     * @mbggenerated
     */
    private Integer rounStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roundsow.roun_id
     *
     * @return the value of roundsow.roun_id
     *
     * @mbggenerated
     */
    public Integer getRounId() {
        return rounId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roundsow.roun_id
     *
     * @param rounId the value for roundsow.roun_id
     *
     * @mbggenerated
     */
    public void setRounId(Integer rounId) {
        this.rounId = rounId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roundsow.roun_img
     *
     * @return the value of roundsow.roun_img
     *
     * @mbggenerated
     */
    public String getRounImg() {
        return rounImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roundsow.roun_img
     *
     * @param rounImg the value for roundsow.roun_img
     *
     * @mbggenerated
     */
    public void setRounImg(String rounImg) {
        this.rounImg = rounImg == null ? null : rounImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roundsow.rpun_type
     *
     * @return the value of roundsow.rpun_type
     *
     * @mbggenerated
     */
    public String getRpunType() {
        return rpunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roundsow.rpun_type
     *
     * @param rpunType the value for roundsow.rpun_type
     *
     * @mbggenerated
     */
    public void setRpunType(String rpunType) {
        this.rpunType = rpunType == null ? null : rpunType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roundsow.roun_createtime
     *
     * @return the value of roundsow.roun_createtime
     *
     * @mbggenerated
     */
    public Date getRounCreatetime() {
        return rounCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roundsow.roun_createtime
     *
     * @param rounCreatetime the value for roundsow.roun_createtime
     *
     * @mbggenerated
     */
    public void setRounCreatetime(Date rounCreatetime) {
        this.rounCreatetime = rounCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roundsow.roun_sort
     *
     * @return the value of roundsow.roun_sort
     *
     * @mbggenerated
     */
    public Integer getRounSort() {
        return rounSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roundsow.roun_sort
     *
     * @param rounSort the value for roundsow.roun_sort
     *
     * @mbggenerated
     */
    public void setRounSort(Integer rounSort) {
        this.rounSort = rounSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roundsow.roun_status
     *
     * @return the value of roundsow.roun_status
     *
     * @mbggenerated
     */
    public Integer getRounStatus() {
        return rounStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roundsow.roun_status
     *
     * @param rounStatus the value for roundsow.roun_status
     *
     * @mbggenerated
     */
    public void setRounStatus(Integer rounStatus) {
        this.rounStatus = rounStatus;
    }
}